export const ERROR_CODES = {
  INVALID_SCENARIO: "INVALID_SCENARIO",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  INVALID_REVIEW_TEXT: "INVALID_REVIEW_TEXT",
  INVALID_WEBHOOK_URL: "INVALID_WEBHOOK_URL",
  INVALID_MCP_REQUEST: "INVALID_MCP_REQUEST",
  INVALID_MCP_SESSION: "INVALID_MCP_SESSION",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ALREADY_PROCESSED: "TASK_ALREADY_PROCESSED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
